import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {

  owner: ["*"],



  supervisor: [

    PERMISSIONS.SALES_VIEW,

    PERMISSIONS.RETURNS_VIEW,
    PERMISSIONS.RETURNS_APPROVE,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_TRANSFER,

    PERMISSIONS.PRODUCTS_VIEW,

    PERMISSIONS.PRICING_VIEW,

    PERMISSIONS.REPORTS_VIEW,

    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.EXPENSES_EDIT
  ],



  branch_manager: [

    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,

    PERMISSIONS.RETURNS_VIEW,
    PERMISSIONS.RETURNS_APPROVE,

    PERMISSIONS.INVENTORY_VIEW,

    PERMISSIONS.PRODUCTS_VIEW,

    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,

    PERMISSIONS.REPORTS_VIEW
  ],



  assistant_manager: [

    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,

    PERMISSIONS.RETURNS_VIEW,
    PERMISSIONS.RETURNS_APPROVE,

    PERMISSIONS.INVENTORY_VIEW,

    PERMISSIONS.PRODUCTS_VIEW,

    PERMISSIONS.EXPENSES_VIEW
  ],



  sales: [

    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,

    PERMISSIONS.RETURNS_VIEW,

    PERMISSIONS.PRODUCTS_VIEW
  ]
};