import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import "../assets/fonts/amiriFont";
import logo from "../assets/logo.png";

// ======================================================
// TRANSLATIONS
// ======================================================

const TEXT = {

  ar: {

    title:
      "التقفيل اليومي",

    subtitle:
      "مراجعة مالية وتسوية الكاش",

    matched:
      "مطابق",

    over:
      "زيادة",

    shortage:
      "عجز",

    branch:
      "الفرع",

    businessDate:
      "تاريخ اليومية",

    createdBy:
      "المستخدم",

    expectedCash:
      "الكاش المتوقع",

    actualCash:
      "الكاش الفعلي",

    difference:
      "الفرق",

    breakdown:
      "التفاصيل المالية",

    item:
      "البند",

    amount:
      "القيمة",

    totalSales:
      "إجمالي المبيعات",

    cashSales:
      "الكاش",

    visaSales:
      "فيزا",

    instapay:
      "انستاباي",

    refunds:
      "المرتجعات",

    expenses:
      "المصروفات",

    loans:
      "السلف",

    bonuses:
      "الحوافز",

    invoices:
      "الفواتير",

    notes:
      "الملاحظات",

    noNotes:
      "لا توجد ملاحظات",

    employee:
      "توقيع الموظف",

    manager:
      "توقيع المدير",

    generated:
      "تم الإنشاء بواسطة ERP System"

  },

  en: {

    title:
      "Daily Closing",

    subtitle:
      "Financial Audit & Cash Reconciliation",

    matched:
      "Matched",

    over:
      "Over",

    shortage:
      "Shortage",

    branch:
      "Branch",

    businessDate:
      "Business Date",

    createdBy:
      "Created By",

    expectedCash:
      "Expected Cash",

    actualCash:
      "Actual Cash",

    difference:
      "Difference",

    breakdown:
      "Financial Breakdown",

    item:
      "Item",

    amount:
      "Amount",

    totalSales:
      "Total Sales",

    cashSales:
      "Cash",

    visaSales:
      "Visa",

    instapay:
      "Instapay",

    refunds:
      "Refunds",

    expenses:
      "Expenses",

    loans:
      "Loans",

    bonuses:
      "Bonuses",

    invoices:
      "Invoices",

    notes:
      "Notes",

    noNotes:
      "No notes provided",

    employee:
      "Employee Signature",

    manager:
      "Manager Signature",

    generated:
      "Generated by ERP System"

  }

};

// ======================================================
// HELPERS
// ======================================================

const safeText = (
  text = ""
) => {

  return String(text || "")
    .trim();

};

const toArabicNumbers = (
  value = ""
) => {

  return String(value)

    .replace(/0/g, "٠")
    .replace(/1/g, "١")
    .replace(/2/g, "٢")
    .replace(/3/g, "٣")
    .replace(/4/g, "٤")
    .replace(/5/g, "٥")
    .replace(/6/g, "٦")
    .replace(/7/g, "٧")
    .replace(/8/g, "٨")
    .replace(/9/g, "٩");

};

const formatMoney = (
  num,
  lang = "ar"
) => {

  const formatted =

    new Intl.NumberFormat(
      "en-US",
      {
        minimumFractionDigits: 0,
        maximumFractionDigits: 0
      }
    ).format(
      Number(num || 0)
    );

  if (lang === "ar") {

    return `${toArabicNumbers(
      formatted
    )} EGP`;

  }

  return `${formatted} EGP`;

};

const getStatus = (
  status,
  lang
) => {

  const t =
    TEXT[lang];

  if (status === "matched") {

    return {

      label:
        t.matched,

      color:
        [22, 163, 74]

    };

  }

  if (status === "over") {

    return {

      label:
        t.over,

      color:
        [245, 158, 11]

    };

  }

  return {

    label:
      t.shortage,

      color:
        [220, 38, 38]

  };

};

// ======================================================
// EXPORT
// ======================================================

export const exportClosingPDF = (
  item,
  lang = "ar"
) => {

  const isArabic =
    lang === "ar";

  const t =
    TEXT[lang];

  const status =
    getStatus(
      item.differenceStatus,
      lang
    );

  // ======================================================
  // PDF
  // ======================================================

  const doc =
    new jsPDF({

      orientation:
        "portrait",

      unit:
        "mm",

      format:
        "a4"

    });

  doc.setFont(
    "Amiri-Regular",
    "normal"
  );

  doc.setLanguage(
    isArabic
      ? "ar"
      : "en"
  );

  

  // ======================================================
  // BACKGROUND
  // ======================================================

  doc.setFillColor(
    248,
    250,
    252
  );

  doc.rect(
    0,
    0,
    210,
    297,
    "F"
  );
  
  // ======================================================
  // STATUS BADGE
  // ======================================================

  doc.setFillColor(
    ...status.color
  );

  doc.roundedRect(

    isArabic
      ? 16
      : 140,

    18,

    58,

    13,

    4,

    4,

    "F"

  );

  doc.setFontSize(11);

  doc.setTextColor(
    255,
    255,
    255
  );

  doc.text(

    safeText(
      status.label
    ),

    isArabic
      ? 45
      : 169,

    26,

    {
      align:
        "center"
    }

  );

  // ======================================================
  // TITLE
  // ======================================================

  doc.setFont(
    "Amiri-Regular",
    "normal"
  );

  doc.setFontSize(24);

  doc.setTextColor(
    15,
    23,
    42
  );

  doc.text(

    safeText(
      t.title
    ),

    isArabic
      ? 190
      : 14,

    26,

    {

      align:

        isArabic
          ? "right"
          : "left"

    }

  );

  // ======================================================
  // SUBTITLE
  // ======================================================

  doc.setFontSize(10);

  doc.setTextColor(
    100,
    116,
    139
  );

  doc.text(

    safeText(
      t.subtitle
    ),

    isArabic
      ? 190
      : 14,

    34,

    {

      align:

        isArabic
          ? "right"
          : "left"

    }

  );

  // ======================================================
  // INFO TABLE
  // ======================================================

  autoTable(doc, {

    startY:
      58,

    theme:
      "grid",

    tableWidth:
      190,

    margin: {
      left: 10,
      right: 10
    },

    styles: {

      font:
        "Amiri-Regular",

      fontStyle:
        "normal",

      fontSize:
        11,

      textColor:
        [15, 23, 42],

      lineColor:
        [226, 232, 240],

      lineWidth:
        0.3,

      fillColor:
        [252, 252, 252],

      cellPadding: {

        top: 5,
        right: 5,
        bottom: 5,
        left: 5

      },

      halign:

        isArabic
          ? "right"
          : "left",

      valign:
        "middle"

    },

    columnStyles: {

      0: {
        cellWidth: 95
      },

      1: {
        cellWidth: 95
      }

    },

    body:

      isArabic

        ? [

            [
              item.branchName || "-",
              safeText(t.branch)
            ],

            [
              item.businessDate || "-",
              safeText(t.businessDate)
            ],

            [
              item.createdBy || "-",
              safeText(t.createdBy)
            ],

            [
              formatMoney(
                item.expectedCash,
                lang
              ),
              safeText(t.expectedCash)
            ],

            [
              formatMoney(
                item.actualCash,
                lang
              ),
              safeText(t.actualCash)
            ],

            [
              formatMoney(
                item.difference,
                lang
              ),
              safeText(t.difference)
            ]

          ]

        : [

            [
              t.branch,
              item.branchName || "-"
            ],

            [
              t.businessDate,
              item.businessDate || "-"
            ],

            [
              t.createdBy,
              item.createdBy || "-"
            ],

            [
              t.expectedCash,
              formatMoney(
                item.expectedCash,
                lang
              )
            ],

            [
              t.actualCash,
              formatMoney(
                item.actualCash,
                lang
              )
            ],

            [
              t.difference,
              formatMoney(
                item.difference,
                lang
              )
            ]

          ]

  });

  // ======================================================
  // BREAKDOWN TITLE
  // ======================================================

  const afterInfoY =
    doc.lastAutoTable.finalY + 16;

  doc.setFontSize(17);

  doc.setTextColor(
    15,
    23,
    42
  );

  doc.text(

    safeText(
      t.breakdown
    ),

    isArabic
      ? 200
      : 10,

    afterInfoY,

    {

      align:

        isArabic
          ? "right"
          : "left"

    }

  );

  // ======================================================
  // BREAKDOWN TABLE
  // ======================================================

  autoTable(doc, {

    startY:
      afterInfoY + 6,

    theme:
      "grid",

    tableWidth:
      190,

    margin: {
      left: 10,
      right: 10
    },

    tableLineColor:
      [226, 232, 240],

    tableLineWidth:
      0.3,

    alternateRowStyles: {

      fillColor:
        [248, 250, 252]

    },

    styles: {

      font:
        "Amiri-Regular",

      fontStyle:
        "normal",

      fontSize:
        11,

      textColor:
        [15, 23, 42],

      lineColor:
        [226, 232, 240],

      lineWidth:
        0.3,

      cellPadding: {

        top: 5,
        right: 5,
        bottom: 5,
        left: 5

      },

      halign:

        isArabic
          ? "right"
          : "left"

    },

    headStyles: {

      font:
        "Amiri-Regular",

      fontStyle:
        "normal",

      fontSize:
        12,

      fillColor:
        [15, 23, 42],

      textColor:
        [252, 252, 252]

    },

    head:

      isArabic

        ? [[

            safeText(
              t.amount
            ),

            safeText(
              t.item
            )

          ]]

        : [[

            t.item,

            t.amount

          ]],

    body:

      isArabic

        ? [

            [
              formatMoney(
                item.totalSales,
                lang
              ),
              safeText(
                t.totalSales
              )
            ],

            [
              formatMoney(
                item.cashSales,
                lang
              ),
              safeText(
                t.cashSales
              )
            ],

            [
              formatMoney(
                item.visaSales,
                lang
              ),
              safeText(
                t.visaSales
              )
            ],

            [
              formatMoney(
                item.instapaySales,
                lang
              ),
              safeText(
                t.instapay
              )
            ],

            [
              formatMoney(
                item.refunds,
                lang
              ),
              safeText(
                t.refunds
              )
            ],

            [
              formatMoney(
                item.expenses,
                lang
              ),
              safeText(
                t.expenses
              )
            ],

            [
              formatMoney(
                item.loans,
                lang
              ),
              safeText(
                t.loans
              )
            ],

            [
              formatMoney(
                item.bonuses,
                lang
              ),
              safeText(
                t.bonuses
              )
            ],

            [
              String(
                item.invoices || 0
              ),
              safeText(
                t.invoices
              )
            ]

          ]

        : [

            [
              t.totalSales,
              formatMoney(
                item.totalSales,
                lang
              )
            ],

            [
              t.cashSales,
              formatMoney(
                item.cashSales,
                lang
              )
            ],

            [
              t.visaSales,
              formatMoney(
                item.visaSales,
                lang
              )
            ],

            [
              t.instapay,
              formatMoney(
                item.instapaySales,
                lang
              )
            ],

            [
              t.refunds,
              formatMoney(
                item.refunds,
                lang
              )
            ],

            [
              t.expenses,
              formatMoney(
                item.expenses,
                lang
              )
            ],

            [
              t.loans,
              formatMoney(
                item.loans,
                lang
              )
            ],

            [
              t.bonuses,
              formatMoney(
                item.bonuses,
                lang
              )
            ],

            [
              t.invoices,
              String(
                item.invoices || 0
              )
            ]

          ]

  });

  // ======================================================
  // NOTES
  // ======================================================

  const afterBreakdownY =
    doc.lastAutoTable.finalY + 16;

  doc.setFontSize(16);

  doc.setTextColor(
    15,
    23,
    42
  );

  doc.text(

    safeText(
      t.notes
    ),

    isArabic
      ? 200
      : 10,

    afterBreakdownY,

    {

      align:

        isArabic
          ? "right"
          : "left"

    }

  );

  // ======================================================
  // NOTES BOX
  // ======================================================

  doc.setFillColor(
    255,
    255,
    255
  );

  doc.roundedRect(
    10,
    afterBreakdownY + 5,
    190,
    28,
    3,
    3,
    "F"
  );

  doc.setDrawColor(
    226,
    232,
    240
  );

  doc.roundedRect(
    10,
    afterBreakdownY + 5,
    190,
    28,
    3,
    3
  );

  doc.setFontSize(11);

  doc.setTextColor(
    71,
    85,
    105
  );

  const noteText =
    safeText(
      item.notes || t.noNotes
    );

  doc.text(

    noteText,

    isArabic
      ? 194
      : 16,

    afterBreakdownY + 16,

    {

      maxWidth:
        175,

      align:

        isArabic
          ? "right"
          : "left"

    }

  );

  // ======================================================
  // SIGNATURES
  // ======================================================

  const signY =
    afterBreakdownY + 58;

  doc.setDrawColor(
    180
  );

  // EMPLOYEE

  doc.line(

    isArabic
      ? 118
      : 20,

    signY,

    isArabic
      ? 180
      : 82,

    signY

  );

  doc.setFontSize(11);

  doc.setTextColor(
    51,
    65,
    85
  );

  doc.text(

    safeText(
      t.employee
    ),

    isArabic
      ? 120
      : 22,

    signY + 8

  );

  // MANAGER

  doc.line(

    isArabic
      ? 20
      : 118,

    signY,

    isArabic
      ? 82
      : 180,

    signY

  );

  doc.text(

    safeText(
      t.manager
    ),

    isArabic
      ? 22
      : 120,

    signY + 8

  );

  // ======================================================
// FOOTER ON ALL PAGES
// ======================================================

const totalPages =
  doc.internal.getNumberOfPages();

for (
  let i = 1;
  i <= totalPages;
  i++
) {

  doc.setPage(i);

  const footerY = 282;

  doc.setDrawColor(
    226,
    232,
    240
  );

  doc.line(
    10,
    footerY,
    200,
    footerY
  );

  doc.setFontSize(9);

  doc.setTextColor(
    148,
    163,
    184
  );

  doc.text(

    safeText(
      t.generated
    ),

    isArabic
      ? 198
      : 12,

    footerY + 6,

    {

      align:

        isArabic
          ? "right"
          : "left"

    }

  );

}


  // ======================================================
// WATERMARK ON ALL PAGES
// ======================================================

const watermarkPages =
  doc.internal.getNumberOfPages();

for (
  let i = 1;
  i <= watermarkPages;
  i++
) {

  doc.setPage(i);

  doc.setGState(
    new doc.GState({
      opacity: 0.06
    })
  );

  doc.addImage(

    logo,

    "PNG",

    50,
    70,
    110,
    110

  );

  doc.setGState(
    new doc.GState({
      opacity: 1
    })
  );

}
  // ======================================================
  // SAVE
  // ======================================================

  doc.save(

    `${
      isArabic
        ? "التقفيل-اليومي"
        : "DailyClosing"
    }_${
      item.businessDate
      || "Report"
    }.pdf`

  );

};